version: 1.5.7.{build}
image: Visual Studio 2015


clone_depth: 1


environment:
  matrix:
  - PlatformToolset: v140_xp
  - PlatformToolset: v120_xp

platform:
    - x64
    - Win32

configuration:
    - Release Unicode
    - Debug Unicode

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd c:\projects\compare-plugin\projects\2013\
    - msbuild Compare.vcxproj /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%"

after_build:
    - cd c:\projects\compare-plugin\
    - ps: >-
        $ComparePluginFileName = "ComparePlugin.$env:PLATFORM.$env:CONFIGURATION.$env:PLATFORMTOOLSET.dll"

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Release Unicode") {
            Push-AppveyorArtifact "Notepad++\plugins\ComparePlugin.dll" -FileName "$ComparePluginFileName"
        }

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Debug Unicode") {
            Push-AppveyorArtifact "Notepad++\plugins\ComparePlugin.dll" -FileName "$ComparePluginFileName"
        }

        if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Release Unicode") {
            Push-AppveyorArtifact "Notepad++\plugins\ComparePlugin.dll" -FileName "$ComparePluginFileName"
        }

        if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Debug Unicode") {
            Push-AppveyorArtifact "Notepad++\plugins\ComparePlugin.dll" -FileName "$ComparePluginFileName"
        }

