version: 1.5.7.{build}
image: Visual Studio 2015

clone_depth: 1

environment:
  matrix:
  - PlatformToolset: v140_xp
  - PlatformToolset: v120_xp

platform:
    - x64
    - x86

configuration:
    - Release Unicode
    - Debug Unicode

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x86" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\projects\2013\
    - msbuild Compare.vcxproj /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        Push-AppveyorArtifact "Notepad++\plugins\ComparePlugin.dll" -FileName ComparePlugin.dll

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release Unicode" -and $env:PLATFORMTOOLSET -eq "v120_xp") {
            $ZipFileName = "ComparePlugin_$($env:APPVEYOR_REPO_TAG_NAME)_$env:PLATFORM.zip"
            Remove-Item .\Notepad++\plugins\*.pdb
            7z a $ZipFileName .\Notepad++\plugins\*
        }

artifacts:
  - path: ComparePlugin_*.zip
    name: releases

deploy:
  provider: GitHub
  auth_token:
    secure: b9E1qivB5Vn1wX4kAT+TFE7JdNjx1CWznNFc1nylaBZxFguRRpe2WV908G8XRfw4 # your encrypted token from GitHub
  artifact: /.ComparePlugin_*\.zip/ # upload all zip packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
